/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f0",
        "surface-dim": "#e3d9c6",
        "surface-bright": "#fff8f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fdf3df",
        "surface-container": "#f7edda",
        "surface-container-high": "#f1e7d4",
        "surface-container-highest": "#ebe1cf",
        "on-surface": "#1f1b10",
        "on-surface-variant": "#51443a",
        "inverse-surface": "#353023",
        "inverse-on-surface": "#faf0dd",
        "outline": "#847469",
        "outline-variant": "#d6c3b6",
        "surface-tint": "#855324",
        "primary": "#552c00",
        "on-primary": "#ffffff",
        "primary-container": "#704214",
        "on-primary-container": "#f1b179",
        "inverse-primary": "#fbb980",
        "secondary": "#775928",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffd79b",
        "on-secondary-container": "#7a5c2b",
        "tertiary": "#373636",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4e4d4d",
        "on-tertiary-container": "#c0bebd",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdcc1",
        "primary-fixed-dim": "#fbb980",
        "on-primary-fixed": "#2e1500",
        "on-primary-fixed-variant": "#693c0e",
        "secondary-fixed": "#ffdeae",
        "secondary-fixed-dim": "#e8c086",
        "on-secondary-fixed": "#281800",
        "on-secondary-fixed-variant": "#5d4213",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1b1b1c",
        "on-tertiary-fixed-variant": "#474746",
        "background": "#fff8f0",
        "on-background": "#1f1b10",
        "surface-variant": "#ebe1cf",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "margin-page": "4rem",
        "sheet-overlap": "-2rem",
        "stack-offset": "4px",
      },
      fontFamily: {
        "display-lg": ["EB Garamond", "serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "body-md": ["Courier Prime", "monospace"],
        "body-sm": ["Courier Prime", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
