spring.application.name=scriptum

#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/scriptum
spring.datasource.username=scriptum
spring.datasource.password=scriptum
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#update limits and storage
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
scriptum.storage.path=/tmp/scriptum

#groq api key and whisper url
groq.api.key=${GROQ_API_KEY}
whisper.local.url=http://localhost:5000

#swagger config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html