spring.application.name=scriptum

spring.datasource.url=jdbc:postgresql://localhost:5432/scriptum
spring.datasource.username=scriptum
spring.datasource.password=scriptum
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

//update limits and storage
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
scriptum.storage.path=/tmp/scriptum